import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: ["intro", "getting-started/quickstart", "getting-started/concepts"],
      collapsed: false,
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/beats-scenes-shots",
        "features/ai-pipeline",
        "features/cinematography",
        "features/actors-characters",
        "features/video-editor",
        "features/integrations",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/first-video",
        "tutorials/script-to-shots",
        "tutorials/custom-actors",
      ],
    },
    {
      type: "category",
      label: "How-To Guides",
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
    {
      type: "category",
      label: "Guides",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Use Cases",
      items: [{ type: "autogenerated", dirName: "use-cases" }],
    },
    {
      type: "category",
      label: "Comparisons",
      items: [{ type: "autogenerated", dirName: "comparisons" }],
    },
    {
      type: "category",
      label: "Enterprise",
      items: [{ type: "autogenerated", dirName: "enterprise" }],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        "roadmap",
        "changelog",
        {
          type: "category",
          label: "Glossary",
          items: [{ type: "autogenerated", dirName: "glossary" }],
        },
      ],
    },
  ],
};

export default sidebars;
